// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: sbin_pb/sbinpb.proto

package sbin_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	City   string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Place  string `protobuf:"bytes,3,opt,name=place,proto3" json:"place,omitempty"`
	Lat    string `protobuf:"bytes,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Long   string `protobuf:"bytes,5,opt,name=long,proto3" json:"long,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sbin_pb_sbinpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_sbin_pb_sbinpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_sbin_pb_sbinpb_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *Location) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *Location) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

type Bin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State    string    `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Level    int32     `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Location *Location `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *Bin) Reset() {
	*x = Bin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sbin_pb_sbinpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bin) ProtoMessage() {}

func (x *Bin) ProtoReflect() protoreflect.Message {
	mi := &file_sbin_pb_sbinpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bin.ProtoReflect.Descriptor instead.
func (*Bin) Descriptor() ([]byte, []int) {
	return file_sbin_pb_sbinpb_proto_rawDescGZIP(), []int{1}
}

func (x *Bin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bin) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Bin) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Bin) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type BinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bin *Bin `protobuf:"bytes,1,opt,name=bin,proto3" json:"bin,omitempty"`
}

func (x *BinRequest) Reset() {
	*x = BinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sbin_pb_sbinpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinRequest) ProtoMessage() {}

func (x *BinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sbin_pb_sbinpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinRequest.ProtoReflect.Descriptor instead.
func (*BinRequest) Descriptor() ([]byte, []int) {
	return file_sbin_pb_sbinpb_proto_rawDescGZIP(), []int{2}
}

func (x *BinRequest) GetBin() *Bin {
	if x != nil {
		return x.Bin
	}
	return nil
}

type BinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BinResponse) Reset() {
	*x = BinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sbin_pb_sbinpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinResponse) ProtoMessage() {}

func (x *BinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sbin_pb_sbinpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinResponse.ProtoReflect.Descriptor instead.
func (*BinResponse) Descriptor() ([]byte, []int) {
	return file_sbin_pb_sbinpb_proto_rawDescGZIP(), []int{3}
}

func (x *BinResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GetFullBinsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	City string `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *GetFullBinsRequest) Reset() {
	*x = GetFullBinsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sbin_pb_sbinpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFullBinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullBinsRequest) ProtoMessage() {}

func (x *GetFullBinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sbin_pb_sbinpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullBinsRequest.ProtoReflect.Descriptor instead.
func (*GetFullBinsRequest) Descriptor() ([]byte, []int) {
	return file_sbin_pb_sbinpb_proto_rawDescGZIP(), []int{4}
}

func (x *GetFullBinsRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetFullBinsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bins   []*Bin `protobuf:"bytes,1,rep,name=bins,proto3" json:"bins,omitempty"`
	NumBin int32  `protobuf:"varint,2,opt,name=num_bin,json=numBin,proto3" json:"num_bin,omitempty"`
}

func (x *GetFullBinsResponse) Reset() {
	*x = GetFullBinsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sbin_pb_sbinpb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFullBinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullBinsResponse) ProtoMessage() {}

func (x *GetFullBinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sbin_pb_sbinpb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullBinsResponse.ProtoReflect.Descriptor instead.
func (*GetFullBinsResponse) Descriptor() ([]byte, []int) {
	return file_sbin_pb_sbinpb_proto_rawDescGZIP(), []int{5}
}

func (x *GetFullBinsResponse) GetBins() []*Bin {
	if x != nil {
		return x.Bins
	}
	return nil
}

func (x *GetFullBinsResponse) GetNumBin() int32 {
	if x != nil {
		return x.NumBin
	}
	return 0
}

var File_sbin_pb_sbinpb_proto protoreflect.FileDescriptor

var file_sbin_pb_sbinpb_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x62, 0x69, 0x6e, 0x5f, 0x70, 0x62, 0x2f, 0x73, 0x62, 0x69, 0x6e, 0x70, 0x62,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x62, 0x69, 0x6e, 0x22, 0x72, 0x0a, 0x08,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67,
	0x22, 0x81, 0x01, 0x0a, 0x03, 0x42, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x62, 0x69,
	0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x0a, 0x42, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x03, 0x62, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x73, 0x62, 0x69, 0x6e, 0x2e, 0x42, 0x69, 0x6e, 0x52, 0x03, 0x62, 0x69, 0x6e, 0x22,
	0x25, 0x0a, 0x0b, 0x42, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c,
	0x6c, 0x42, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x22, 0x4d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x42, 0x69, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x62, 0x69, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73, 0x62, 0x69, 0x6e, 0x2e, 0x42, 0x69, 0x6e,
	0x52, 0x04, 0x62, 0x69, 0x6e, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x5f, 0x62, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x42, 0x69, 0x6e, 0x32,
	0x82, 0x01, 0x0a, 0x0a, 0x42, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6e, 0x12, 0x10, 0x2e, 0x73, 0x62,
	0x69, 0x6e, 0x2e, 0x42, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e,
	0x73, 0x62, 0x69, 0x6e, 0x2e, 0x42, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x42, 0x69, 0x6e, 0x73, 0x12,
	0x18, 0x2e, 0x73, 0x62, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x42, 0x69,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x62, 0x69, 0x6e,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x42, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x73, 0x62, 0x69, 0x6e, 0x5f, 0x70, 0x62, 0x3b,
	0x73, 0x62, 0x69, 0x6e, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sbin_pb_sbinpb_proto_rawDescOnce sync.Once
	file_sbin_pb_sbinpb_proto_rawDescData = file_sbin_pb_sbinpb_proto_rawDesc
)

func file_sbin_pb_sbinpb_proto_rawDescGZIP() []byte {
	file_sbin_pb_sbinpb_proto_rawDescOnce.Do(func() {
		file_sbin_pb_sbinpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_sbin_pb_sbinpb_proto_rawDescData)
	})
	return file_sbin_pb_sbinpb_proto_rawDescData
}

var file_sbin_pb_sbinpb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sbin_pb_sbinpb_proto_goTypes = []interface{}{
	(*Location)(nil),            // 0: sbin.Location
	(*Bin)(nil),                 // 1: sbin.Bin
	(*BinRequest)(nil),          // 2: sbin.BinRequest
	(*BinResponse)(nil),         // 3: sbin.BinResponse
	(*GetFullBinsRequest)(nil),  // 4: sbin.GetFullBinsRequest
	(*GetFullBinsResponse)(nil), // 5: sbin.GetFullBinsResponse
}
var file_sbin_pb_sbinpb_proto_depIdxs = []int32{
	0, // 0: sbin.Bin.location:type_name -> sbin.Location
	1, // 1: sbin.BinRequest.bin:type_name -> sbin.Bin
	1, // 2: sbin.GetFullBinsResponse.bins:type_name -> sbin.Bin
	2, // 3: sbin.BinService.CreateBin:input_type -> sbin.BinRequest
	4, // 4: sbin.BinService.GetFullBins:input_type -> sbin.GetFullBinsRequest
	3, // 5: sbin.BinService.CreateBin:output_type -> sbin.BinResponse
	5, // 6: sbin.BinService.GetFullBins:output_type -> sbin.GetFullBinsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sbin_pb_sbinpb_proto_init() }
func file_sbin_pb_sbinpb_proto_init() {
	if File_sbin_pb_sbinpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sbin_pb_sbinpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sbin_pb_sbinpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sbin_pb_sbinpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sbin_pb_sbinpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sbin_pb_sbinpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFullBinsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sbin_pb_sbinpb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFullBinsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sbin_pb_sbinpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sbin_pb_sbinpb_proto_goTypes,
		DependencyIndexes: file_sbin_pb_sbinpb_proto_depIdxs,
		MessageInfos:      file_sbin_pb_sbinpb_proto_msgTypes,
	}.Build()
	File_sbin_pb_sbinpb_proto = out.File
	file_sbin_pb_sbinpb_proto_rawDesc = nil
	file_sbin_pb_sbinpb_proto_goTypes = nil
	file_sbin_pb_sbinpb_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BinServiceClient is the client API for BinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BinServiceClient interface {
	CreateBin(ctx context.Context, in *BinRequest, opts ...grpc.CallOption) (*BinResponse, error)
	GetFullBins(ctx context.Context, in *GetFullBinsRequest, opts ...grpc.CallOption) (*GetFullBinsResponse, error)
}

type binServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBinServiceClient(cc grpc.ClientConnInterface) BinServiceClient {
	return &binServiceClient{cc}
}

func (c *binServiceClient) CreateBin(ctx context.Context, in *BinRequest, opts ...grpc.CallOption) (*BinResponse, error) {
	out := new(BinResponse)
	err := c.cc.Invoke(ctx, "/sbin.BinService/CreateBin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binServiceClient) GetFullBins(ctx context.Context, in *GetFullBinsRequest, opts ...grpc.CallOption) (*GetFullBinsResponse, error) {
	out := new(GetFullBinsResponse)
	err := c.cc.Invoke(ctx, "/sbin.BinService/GetFullBins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BinServiceServer is the server API for BinService service.
type BinServiceServer interface {
	CreateBin(context.Context, *BinRequest) (*BinResponse, error)
	GetFullBins(context.Context, *GetFullBinsRequest) (*GetFullBinsResponse, error)
}

// UnimplementedBinServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBinServiceServer struct {
}

func (*UnimplementedBinServiceServer) CreateBin(context.Context, *BinRequest) (*BinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBin not implemented")
}
func (*UnimplementedBinServiceServer) GetFullBins(context.Context, *GetFullBinsRequest) (*GetFullBinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullBins not implemented")
}

func RegisterBinServiceServer(s *grpc.Server, srv BinServiceServer) {
	s.RegisterService(&_BinService_serviceDesc, srv)
}

func _BinService_CreateBin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinServiceServer).CreateBin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sbin.BinService/CreateBin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinServiceServer).CreateBin(ctx, req.(*BinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinService_GetFullBins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFullBinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinServiceServer).GetFullBins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sbin.BinService/GetFullBins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinServiceServer).GetFullBins(ctx, req.(*GetFullBinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BinService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sbin.BinService",
	HandlerType: (*BinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBin",
			Handler:    _BinService_CreateBin_Handler,
		},
		{
			MethodName: "GetFullBins",
			Handler:    _BinService_GetFullBins_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sbin_pb/sbinpb.proto",
}
